version: '3.8'

services:
  backend:
    image: docker.io/lykny97/takingnote-backend:latest
    container_name: takingnote-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      JWT_SECRET: ${JWT_SECRET}
      PORT: 3000
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:3003}
    expose:
      - "3000"
    networks:
      - takingnote-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
    labels:
      - "coolify.managed=true"
      - "coolify.type=application"
      - "coolify.name=takingnote-backend"
      - "coolify.port=3000"

networks:
  takingnote-network:
    external: true
