version: '3.8'

services:
  frontend:
    image: docker.io/lykny97/takingnote-frontend:latest
    container_name: takingnote-frontend
    restart: unless-stopped
    ports:
      - "80:3000"
    networks:
      - takingnote-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "coolify.managed=true"
      - "coolify.type=application"
      - "coolify.name=takingnote-frontend"

networks:
  takingnote-network:
    external: true
